@echo off
cd python_backend
echo Starting Python Face Recognition Service...
echo Installing dependencies...
pip install flask flask-cors requests python-dotenv pillow
echo Starting service on port 8000...
python app.py
pause
