[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 9600
upload_port = COM7
monitor_port = COM7

lib_deps = 
    bblanchon/ArduinoJson@^6.21.3
    marian-craciunescu/ESP32Ping@^1.7
    markruys/arduino-DHT@^1.0.9
    miguelbalboa/MFRC522@^1.4.10
    links2004/WebSockets@^2.4.0
